export const IPC_CHANNELS = {
  openFile: "suwol:open-file",
  openFolder: "suwol:open-folder",
  openRecent: "suwol:open-recent",
  openDroppedPaths: "suwol:open-dropped-paths",
  getLocaleInfo: "app:get-locale-info",
  getPreferences: "suwol:get-preferences",
  getLanguage: "settings:get-language",
  setLanguage: "settings:set-language",
  setTheme: "suwol:set-theme",
  updatePanelPreferences: "settings:update-panel-preferences",
  updateChromePreferences: "settings:update-chrome-preferences",
  updateViewerPreferences: "settings:update-viewer-preferences",
  updateUpdatePreferences: "update:setPreferences",
  toggleFullscreen: "app:toggleFullscreen",
  setFullscreen: "app:setFullscreen",
  getFullscreenState: "app:getFullscreenState",
  fullscreenChanged: "app:onFullscreenChanged",
  openSystemSettings: "app:open-system-settings",
  openReleases: "app:open-releases",
  copyExecutablePath: "app:copy-executable-path",
  getRuntimeInfo: "app:get-runtime-info",
  openLogsFolder: "app:open-logs-folder",
  getLogInfo: "app:get-log-info",
  resetSettings: "settings:reset",
  getCacheStats: "cache:get-stats",
  clearThumbnailCache: "cache:clear-thumbnails",
  cleanupThumbnailCache: "cache:cleanup-thumbnails",
  restartInSafeMode: "app:restart-in-safe-mode",
  writeRendererLog: "app:write-renderer-log",
  rendererReady: "app:renderer-ready",
  openLibraryResult: "suwol:open-library-result",
  openError: "suwol:open-error",
  getMetadata: "suwol:get-metadata",
  getUpdateStatus: "update:getStatus",
  checkForUpdates: "update:check",
  updateProgress: "update:progress",
  downloadUpdate: "update:download",
  installUpdate: "update:install"
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
